[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "jwt_auth"
[http]
internalPort = 8080

[[services.ports]]
port = 8080